### ISSUE TITLE
Fix PyPI documentation format

### ISSUE THREAD

**Issue by RustyBower** [RustyBower/sopel-bucket#9]
With the conversion from rst to md, it looks like the documentation format on https://pypi.org/project/sopel-modules.bucket/ broke

**Comment by dgw** [comment]
I wonder if it's not actually https://github.com/pypa/warehouse/issues/3664 since the correct setup argument is set: https://github.com/sopel-irc/sopel-bucket/blob/f92e1082d009541462bddb0532250501e485251d/setup.py#L33

Could do a post-release that updates the repository URL to point at @sopel-irc and conveniently also gives the release toolchain a chance to build the metadata correctly this time?

**Comment by dgw** [comment]
I don't see any problems over there at the moment; the PyPI description renders the same as the README here.

We can reopen if the problem comes back, but this plugin's due for a packaging revamp anyway now that Sopel 8 is out + we encourage use of entrypoints instead of the `sopel_modules` namespace these days.
